### ISSUE TITLE
[feat] 커스텀 원형 그래프 만들기 🔨

### ISSUE THREAD

**Issue by Jokwanhee** [Team-Motivoo/Motivoo-Android#13]
## ❗ 이슈 요약
다음과 같은 원형 그래프를 만들기 위해서 커스텀 뷰로 제작하려고 한다. 고려해야할 부분은 다음과 같다.
- 회색 부분 원형 막대
- 하늘색 부분 원형 막대
- 이미지 로고
- 원형 그래프 내부 걸음 횟수 텍스트

![image](https://github.com/Team-Motivoo/Motivoo-Android/assets/90740783/9ce4a49f-22e7-448f-9371-60b13b013b1a)

## 📝 todo
- [x] 회색 부분 원형 막대
- [x] 하늘색 부분 원형 막대
- [x] 이미지 로고
- [x] 원형 그래프 내부 걸음 횟수 텍스트
- [x] 0~100% 그래프 동적 바인딩
- [x] 걸음 횟수만큼 텍스트 동적 바인딩
- [x] 기기 크기 별 대응 (커스텀 뷰를 제작할 때, 하드코딩하지 않고 유연하게 작성한다.)
