### ISSUE TITLE
[feat] 만보기 기능 구현 🦶

### ISSUE THREAD

**Issue by Jokwanhee** [Team-Motivoo/Motivoo-Android#18]
## ❗ 이슈 요약
- 안드로이드 핸드폰 내장 센서 **STEP_COUNTER_SENSOR** 사용하기
- 백그라운드 작업 - **비동기 & 포그라운드 서비스** 사용하기
  - Coroutine
  - Foreground Service
- **SharedPreferences** 사용하기
- 포그라운드 서비스 관련하여 Notification 적용 必
- API 33 이상 POST_NOTIFICATIONS 권한 必
- API 28 이상 FOREGROUND_SERVICE 권한 必
- API 26 이상 Notification Channel 必

---
**[2024.01.08 Edit]**
### TYPE_STEP_COUNT 센서에서 TYPE_STEP_DETECTOR 센서로 변경한다.   

이유는 TYPE_STEP_COUNT 센서를 등록해서 사용했을 때, 해당 센서 리스너의 오버라이드 함수가 호출되어서 걷지도 않았는데 +1 이 되는 것을 알았다.
하지만, TYPE_STEP_DETECTOR 센서는 보행 감지 센서 이므로, 보행자가 걸어다니는 것을 자이로 센서가 감지했을 때 리스너의 오버라이드 함수를 호출한다. 그렇기 때문에 걷지도 않았는데 무분별한 +1 이 되는 문제를 개선할 수 있다. 즉, 걸을 때만 센서 값을 가져올 수 있다!

---

### Android 8 (API 26) 이상 대응하기
- Notification 채널 만들기
```kotlin
val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
manager.createNotificationChannel(
    NotificationChannel("1", "포그라운드 서비스", NotificationManager.IMPORTANCE_NONE)
)
```

### Android 9 (API 28) 이상 대응하기
- FOREGROUND_SERVICE 권한 Manifest 에 넣기
```kotlin
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

### Android 10 (API  29) 이상 대응하기
- ACTIVITY_RECOGNITION 권한 체크하기
```kotlin
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
```
```kotlin
checkSelfPermission(context, Manifest.permission.ACTIVITY_RECOGNITION)
```

### Android 13 (API 33) 이상 대응하기
- POST_NOTIFICATIONS  권한 체크
```kotlin
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```
```kotlin
checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS)
```

### Android 14 (API 34) 이상 대응하기
- broadcastReceiver package 이름 적기
```kotlin
val intentTest = Intent().apply {
    `package` = this@StepCountService.packageName
}
sendBroadcast(intentTest)
```
- Foreground Service 유형 지정하기 (알림)
```kotlin
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />
```
```kotlin
<service android:name=".step_count.StepCountService"
    android:exported="false"
    android:foregroundServiceType="dataSync"/>
```
```kotlin
startForeground(1, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC)
```

--- 
### 뭐세요? 😠 
TYPE_STEP_COUNTET 센서가 제대로 동작하지 않는 기기가 존재하는 건가? 
Pixel 7 Pro API 33 애뮬레이터에서 sensor or listener is null 이라는 에러문구가 발생했다.
뭐지? 
반면에, 실제 기기 Galaxy S23 Ultra / Android 14 에서는 해당 센서가 잘 동작한다..

## 📝 todo
- [x]  API 33 이상 POST_NOTIFICATIONS 권한 
- [x] API 28 이상 FOREGROUND_SERVICE 권한
- [x] 백그라운드 작업 - 비동기 & 포그라운드 서비스 
- [x] STEP_COUNTER_SENSOR
- [x] Notification
