### ISSUE TITLE
[UI] 온보딩 뷰 작업

### ISSUE THREAD

**Issue by l2zh** [Team-Motivoo/Motivoo-Android#20]
## ❗ 이슈 요약

- 온보딩 뷰 작업

## 📝 todo

- [x] 온보딩 질문 1 애니메이션
- [x] 단일 선택
- [x] 온보딩 진행 프로그래스 바 애니메이션
- [x] 온보딩 질문 5 다중 선택
