### ISSUE TITLE
[UI] 최종 홈 디자인 구현 

### ISSUE THREAD

**Issue by Jokwanhee** [Team-Motivoo/Motivoo-Android#28]
## ❗ 이슈 요약
- 내부 원형 프로그래스 바 1개
- 나 (자식 또는 부모) 원형 프로그래스 바 1개
- 상대 (자식 또는 부모) 원형 프로그래스 바 1개
- 원형 프로그래스 바를 따라다니는 "나"의 이미지
- 원형 프로그래스 바를 따라다니는 "상대"의 이미지
- 미션 선택 전 -> 미션 선택 후 애니메이션 적용해보기 

![image](https://github.com/Team-Motivoo/Motivoo-Android/assets/90740783/bc1425c0-39aa-4771-a4c1-94b7fd7b3838)

### 미션 선택 전 UI
![image](https://github.com/Team-Motivoo/Motivoo-Android/assets/90740783/fc0dec4e-e19c-4adc-aa91-4a9e85d0c700)

### 미션 선택 후 UI
![image](https://github.com/Team-Motivoo/Motivoo-Android/assets/90740783/0b71f3b2-0ca5-4abc-9fec-5d1fdcbbbe4d)

## 📝 todo
- [x] 내부 원형 프로그래스 바 1개
- [x] 나 (자식 또는 부모) 원형 프로그래스 바 1개
- [x] 상대 (자식 또는 부모) 원형 프로그래스 바 1개
- [x] 원형 프로그래스 바를 따라다니는 "나"의 이미지
- [x] 원형 프로그래스 바를 따라다니는 "상대"의 이미지
- [x] 미션 선택 전 UI
- [x] 미션 선택 후 UI
- [x] 애니메이션 적용
