### ISSUE TITLE
[QA] 온보딩 

### ISSUE THREAD

**Issue by l2zh** [Team-Motivoo/Motivoo-Android#69]
## ❗ 이슈 요약

제목 그대로

## 📝 todo

- [x] 권한 뷰 분기처리 추가 (권한 거절 후 앱 재진입 시 다음 페이지 넘어가게 flag 처리)
- [x] CTA 버튼 그림자 효과 제거
- [x] 다른 뷰로 넘어갈 때마다 Empty View가 나옴 -> UIstate 적용
