### ISSUE TITLE
[docs] Readme 꾸미기

### ISSUE THREAD

**Issue by Jokwanhee** [Team-Motivoo/Motivoo-Android#8]
## ❗ 이슈 요약

Readme 꾸미기!
- 프로젝트 이름
- 프로젝트 설명
- 개발 라이브러리 및 테스트, 분석 도구
- 아키텍처
- 패키지 구조
- 깃 컨벤션 & 코드 컨벤션
- 개발자

## 📝 todo

- [x] 프로젝트 이름
- [x] 프로젝트 설명
- [x] 개발 라이브러리 및 테스트, 분석 도구
- [x] 아키텍처
- [x] 패키지 구조
- [x] 깃 컨벤션 & 코드 컨벤션
- [x] 개발자

-- 피드백 --
- [x] 칸반보드 추가
- [x] 프로젝트 핵심가치 추가
