### ISSUE TITLE
[refactor] 온보딩 로직 수정

### ISSUE THREAD

**Issue by l2zh** [Team-Motivoo/Motivoo-Android#95]
## ❗ 이슈 요약

온보딩 로직 수정

## 📝 todo

- [x] 생명주기 주입 고치기
- [x]  flow 수집 조건 제한
- [x] 이벤트 기반 상태 처리 (화면 이동)
