### ISSUE TITLE
[refactor] 원형 프로그래스 바 커스텀 뷰

### ISSUE THREAD

**Issue by Jokwanhee** [Team-Motivoo/Motivoo-Android#98]
## ❗ 이슈 요약
- 원형 프로그래스 바 커스텀 뷰 코드 리팩토링하기! 

## 📝 todo
> Edited 24.02.21
- [x] 코드 리팩토링
- [x] 디자인 컴포넌트 모듈화
- [x] 사용자 자식/부모 이미지 분기 로직 작
- [x] 가운데 하얀색 원 겹치지 않게 Z축 밑으로 내리기
- [x] 이미지 만나는 위치에서 BACK 되는 UI 문제 개선 (호 길이 계산으로 해결)
- [x] 이미지 프로그래스 바 정중앙에 위치하도록 이미지 위치 조정
